### PR TITLE
added ringtail auth

### PR DESCRIPTION
**Pull request by adampaulberg**
- added support for rintail auth https://github.com/fti-technology/ringtail-login/pull/1
- building out redirect url for login
- updated more ```var``` to ```let```
- moved .migrate to data folder. 
- background check to see if browser has been logged out
- ringtail login support
- login can accept JWT

**MANUALLY MOVE ```.migrate``` TO DATA FOLDER IF YOU HAVE PREVIOUS RUN THIS PROJECT**

### CODE REVIEW

**Comment by jakebrown58** [comment]
Should there be changes to the readme for this?

**Comment by adampaulberg** [comment]
@jakebrown58 added

**Comment by adampaulberg** [comment]
@jakebrown58 merged

**Comment by jakebrown58** [comment]
why is there a private key in source in a public repo?

**Comment by jakebrown58** [comment]
looks good at this point.

**Pull request merged**
